"""Streamlit frontend. Run:  streamlit run frontend/streamlit_app.py"""
import os

import requests
import streamlit as st

API_URL = os.getenv("API_URL", "http://localhost:8000")

st.set_page_config(page_title="GitHub Repo Explainer", page_icon="🧠", layout="centered")
st.title("🧠 GitHub Repository Code Explainer")
st.caption("Runs 100% locally: GitPython → local LLM → FastAPI → Streamlit")

# Backend status
try:
    info = requests.get(f"{API_URL}/health", timeout=3).json()
    st.sidebar.success(f"Backend online\n\nLLM: {info['model']} ({info['backend']})")
except Exception:
    st.sidebar.error("Backend offline. Start it with:\n\n`uvicorn app.main:app --port 8000`")

repo_url = st.text_input(
    "GitHub repository URL", placeholder="https://github.com/username/repository"
)

if st.button("Explain this GitHub Repository", type="primary"):
    if not repo_url.strip():
        st.warning("Please enter a repository URL.")
    else:
        with st.spinner("Cloning repo and asking the local LLM... (can take a minute or two)"):
            try:
                r = requests.post(
                    f"{API_URL}/explain", json={"repo_url": repo_url}, timeout=900
                )
            except requests.ConnectionError:
                st.error("Cannot reach the backend. Is uvicorn running?")
                st.stop()

        if r.status_code == 200:
            data = r.json()
            st.success(f"Explanation generated by `{data['model']}`")
            st.markdown(data["explanation"])
            with st.expander(f"Files analyzed ({len(data['files_analyzed'])})"):
                for f in data["files_analyzed"]:
                    st.code(f, language=None)
        else:
            detail = r.json().get("detail", r.text)
            if isinstance(detail, list):  # Pydantic validation errors
                detail = detail[0].get("msg", str(detail))
            st.error(detail)
